---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - image: docker.io/nickvab/stress:v1
    resources:
        requests:
          cpu: 100m
          memory: 200M
        limits:
          cpu: 100
          memory: 200M
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always

