db_all:
  vars:
    ansible_user: root
    ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q jump_sa@178.124.206.53 -p 22510"'
  hosts:
    host3:
      ansible_host: 192.168.203.3
    mysql:
      ansible_host: 192.168.202.3
